# Generated by Django 2.2.3 on 2019-08-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190825_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ManyToManyField(to='api.Photo'),
        ),
    ]
