# Generated by Django 2.2.3 on 2019-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineRieltor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
