# Generated by Django 2.2.3 on 2019-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190825_2129'),
        ('bot', '0005_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.ManyToManyField(to='api.TelegramUser')),
            ],
        ),
    ]
