# Generated by Django 2.2.3 on 2019-11-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='regionOwner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.MainRegion'),
            preserve_default=False,
        ),
    ]
