# Generated by Django 2.2.2 on 2019-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysystem',
            name='token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='setting',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
