# Generated by Django 2.2.2 on 2019-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default='', verbose_name='Phone Number'),
        ),
    ]
