# Generated by Django 2.2.2 on 2019-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190613_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, verbose_name='Phone Number'),
        ),
    ]
