# Generated by Django 2.2.3 on 2019-08-25 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_telegramuser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=10, verbose_name='Операция')),
                ('_property', models.CharField(max_length=30, verbose_name='Тип недвижимости')),
                ('title', models.TextField(verbose_name='Описание')),
                ('region', models.CharField(max_length=30, verbose_name='Район')),
                ('reference', models.CharField(max_length=30, verbose_name='Ориентир')),
                ('location_X', models.FloatField(verbose_name='Локация: широта')),
                ('location_Y', models.FloatField(verbose_name='Локация: долгота')),
                ('room_count', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('square', models.PositiveIntegerField(verbose_name='Общая площадь')),
                ('area', models.PositiveIntegerField(verbose_name='Количество соток')),
                ('state', models.CharField(max_length=30, verbose_name='Состояние')),
                ('ammount', models.CharField(max_length=255, verbose_name='Цена')),
                ('add_info', models.TextField(verbose_name='Инфо')),
                ('contact', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TelegramUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='published_date',
        ),
        migrations.AddField(
            model_name='order',
            name='_property',
            field=models.CharField(default='Участок', max_length=30, verbose_name='Тип недвижимости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='_type',
            field=models.CharField(default='sale', max_length=10, verbose_name='Операция'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='order',
            name='add_info',
            field=models.TextField(default='', verbose_name='Инфо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ammount',
            field=models.CharField(default=0, max_length=255, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество соток'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='location_X',
            field=models.FloatField(default=0, verbose_name='Локация: широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='location_Y',
            field=models.FloatField(default=1, verbose_name='Локация: долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(default='', max_length=30, verbose_name='Ориентир'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='', max_length=30, verbose_name='Район'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='room_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Количество комнат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='square',
            field=models.PositiveIntegerField(default=1, verbose_name='Общая площадь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Новое', max_length=30, verbose_name='Состояние'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='order',
            name='pro_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.TemporaryOrder'),
            preserve_default=False,
        ),
    ]
