# Generated by Django 2.2.3 on 2019-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_onlinerieltororder_onlinerieltortemporaryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinerieltor',
            name='description_UZ',
            field=models.TextField(default='None', verbose_name='Описание УЗБ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlinerieltor',
            name='description',
            field=models.TextField(verbose_name='Описание РУС'),
        ),
    ]
