# Generated by Django 2.2.3 on 2019-09-07 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190906_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
