# Generated by Django 2.2.3 on 2019-09-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_telegramuser_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerieltororder',
            name='pro_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OnlineRieltorTemporaryOrder'),
        ),
    ]
