# Generated by Django 2.2.3 on 2019-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190911_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinerieltororder',
            name='main_state',
            field=models.CharField(default=' ', max_length=30, verbose_name='Состояние ремонта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinerieltortemporaryorder',
            name='main_state',
            field=models.CharField(default=' ', max_length=30, verbose_name='Состояние ремонта'),
            preserve_default=False,
        ),
    ]
