# Generated by Django 2.2.3 on 2019-09-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190913_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerieltororder',
            name='area',
            field=models.CharField(max_length=255, verbose_name='Количество соток'),
        ),
        migrations.AlterField(
            model_name='onlinerieltororder',
            name='floor',
            field=models.CharField(max_length=255, verbose_name='Этаж квартиры'),
        ),
        migrations.AlterField(
            model_name='onlinerieltororder',
            name='main_floor',
            field=models.CharField(max_length=255, verbose_name='Количество этажей в доме'),
        ),
        migrations.AlterField(
            model_name='onlinerieltororder',
            name='room_count',
            field=models.CharField(max_length=255, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='onlinerieltororder',
            name='square',
            field=models.CharField(max_length=255, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='onlinerieltortemporaryorder',
            name='area',
            field=models.CharField(max_length=255, verbose_name='Количество соток'),
        ),
        migrations.AlterField(
            model_name='onlinerieltortemporaryorder',
            name='floor',
            field=models.CharField(max_length=255, verbose_name='Этаж квартиры'),
        ),
        migrations.AlterField(
            model_name='onlinerieltortemporaryorder',
            name='main_floor',
            field=models.CharField(max_length=255, verbose_name='Количество этажей в доме'),
        ),
        migrations.AlterField(
            model_name='onlinerieltortemporaryorder',
            name='room_count',
            field=models.CharField(max_length=255, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='onlinerieltortemporaryorder',
            name='square',
            field=models.CharField(max_length=255, verbose_name='Общая площадь'),
        ),
    ]
