# Generated by Django 2.2.3 on 2019-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190930_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonrieltoruser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='order',
            name='show',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
