# Generated by Django 2.2.3 on 2019-10-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_onlinerieltor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerieltor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
