# Generated by Django 2.2.3 on 2019-10-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonrieltoruser',
            name='rieltor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OnlineRieltor'),
        ),
    ]
